<a href="https://colab.research.google.com/github/Aashrit77/Python/blob/main/Recommendation_systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
movie = pd.read_csv("/content/Movie.csv")
movie.head(-5)

      userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8982    7061  GoldenEye (1995)     4.0
8983    7070  GoldenEye (1995)     3.0
8984    7077  GoldenEye (1995)     4.0
8985    7080  GoldenEye (1995)     5.0
8986    7085  GoldenEye (1995)     3.0

[8987 rows x 3 columns]

In [4]:
#to check the number of unique users in my dataset:
len(movie.userId.unique())

4081

In [5]:
len(movie.movie.unique())

10

In [6]:
#we will create our user-item interaction matrix:
user_movie = movie.pivot(index="userId",
                         columns="movie",
                         values="rating").reset_index(drop=True)

In [7]:
user_movie

movie  Father of the Bride Part II (1995)  ...  Waiting to Exhale (1995)
0                                     NaN  ...                       NaN
1                                     NaN  ...                       NaN
2                                     NaN  ...                       NaN
3                                     NaN  ...                       NaN
4                                     NaN  ...                       NaN
...                                   ...  ...                       ...
4076                                  4.0  ...                       NaN
4077                                  3.5  ...                       NaN
4078                                  NaN  ...                       NaN
4079                                  NaN  ...                       NaN
4080                                  NaN  ...                       NaN

[4081 rows x 10 columns]

In [11]:
user_movie.index = movie.userId.unique()

In [12]:
user_movie

movie  Father of the Bride Part II (1995)  ...  Waiting to Exhale (1995)
3                                     NaN  ...                       NaN
6                                     NaN  ...                       NaN
8                                     NaN  ...                       NaN
10                                    NaN  ...                       NaN
11                                    NaN  ...                       NaN
...                                   ...  ...                       ...
7044                                  4.0  ...                       NaN
7070                                  3.5  ...                       NaN
7080                                  NaN  ...                       NaN
7087                                  NaN  ...                       NaN
7105                                  NaN  ...                       NaN

[4081 rows x 10 columns]

In [14]:
user_movie.fillna(0,inplace=True)

In [15]:
user_movie

movie  Father of the Bride Part II (1995)  ...  Waiting to Exhale (1995)
3                                     0.0  ...                       0.0
6                                     0.0  ...                       0.0
8                                     0.0  ...                       0.0
10                                    0.0  ...                       0.0
11                                    0.0  ...                       0.0
...                                   ...  ...                       ...
7044                                  4.0  ...                       0.0
7070                                  3.5  ...                       0.0
7080                                  0.0  ...                       0.0
7087                                  0.0  ...                       0.0
7105                                  0.0  ...                       0.0

[4081 rows x 10 columns]

In [17]:
#calculating the cosine similarity between users:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine,correlation

In [18]:
#the reason we are using 1- is because we want to find the similarity and not the dissimilarity:
user_sim = 1-pairwise_distances(user_movie.values, metric="cosine")

In [19]:
user_sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.55337157],
       [0.        , 1.        , 0.        , ..., 0.45883147, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       ...,
       [0.        , 0.45883147, 0.45883147, ..., 1.        , 0.45883147,
        0.47607054],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       [0.55337157, 0.        , 0.62254302, ..., 0.47607054, 0.62254302,
        1.        ]])

In [20]:
user_sim_df = pd.DataFrame(user_sim)

In [21]:
user_sim_df

          0         1         2     ...      4078      4079      4080
0     1.000000  0.000000  0.000000  ...  0.000000  0.000000  0.553372
1     0.000000  1.000000  0.000000  ...  0.458831  0.000000  0.000000
2     0.000000  0.000000  1.000000  ...  0.458831  1.000000  0.622543
3     0.000000  0.000000  0.000000  ...  0.619422  0.000000  0.000000
4     1.000000  0.000000  0.000000  ...  0.000000  0.000000  0.553372
...        ...       ...       ...  ...       ...       ...       ...
4076  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
4077  0.000000  0.000000  0.752577  ...  0.345306  0.752577  0.468511
4078  0.000000  0.458831  0.458831  ...  1.000000  0.458831  0.476071
4079  0.000000  0.000000  1.000000  ...  0.458831  1.000000  0.622543
4080  0.553372  0.000000  0.622543  ...  0.476071  0.622543  1.000000

[4081 rows x 4081 columns]

In [23]:
user_sim_df.index = movie.userId.unique()
user_sim_df.columns = movie.userId.unique()

In [24]:
user_sim_df

          3         6         8     ...      7080      7087      7105
3     1.000000  0.000000  0.000000  ...  0.000000  0.000000  0.553372
6     0.000000  1.000000  0.000000  ...  0.458831  0.000000  0.000000
8     0.000000  0.000000  1.000000  ...  0.458831  1.000000  0.622543
10    0.000000  0.000000  0.000000  ...  0.619422  0.000000  0.000000
11    1.000000  0.000000  0.000000  ...  0.000000  0.000000  0.553372
...        ...       ...       ...  ...       ...       ...       ...
7044  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
7070  0.000000  0.000000  0.752577  ...  0.345306  0.752577  0.468511
7080  0.000000  0.458831  0.458831  ...  1.000000  0.458831  0.476071
7087  0.000000  0.000000  1.000000  ...  0.458831  1.000000  0.622543
7105  0.553372  0.000000  0.622543  ...  0.476071  0.622543  1.000000

[4081 rows x 4081 columns]

In [25]:
user_sim_df.iloc[0:5,0:5]

     3    6    8    10   11
3   1.0  0.0  0.0  0.0  1.0
6   0.0  1.0  0.0  0.0  0.0
8   0.0  0.0  1.0  0.0  0.0
10  0.0  0.0  0.0  1.0  0.0
11  1.0  0.0  0.0  0.0  1.0

In [27]:
np.fill_diagonal(user_sim,0)

In [28]:
user_sim_df.iloc[0:5,0:5]

     3    6    8    10   11
3   0.0  0.0  0.0  0.0  1.0
6   0.0  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0
11  1.0  0.0  0.0  0.0  0.0

In [30]:
user_sim_df.idxmax(axis=1)[0:5]

3       11
6      168
8       16
10    4047
11       3
dtype: int64

In [37]:
movie[(movie["userId"]==8) | (movie["userId"]==16)]

      userId                    movie  rating
2          8         Toy Story (1995)     4.0
8         16         Toy Story (1995)     3.0
3727       8  Grumpier Old Men (1995)     5.0
5205       8              Heat (1995)     3.0
5207      16              Heat (1995)     3.0
7445       8         GoldenEye (1995)     4.0

In [42]:
#IBCF
# fetching ratng for sabrina
toy_user_rating = user_movie["Sabrina (1995)"]

In [43]:
toy_user_rating

3       0.0
6       0.0
8       0.0
10      0.0
11      0.0
       ...
7044    0.0
7070    0.0
7080    3.0
7087    0.0
7105    4.0
Name: Sabrina (1995), Length: 4081, dtype: float64

In [44]:
similar_t = user_movie.corrwith(toy_user_rating)

In [45]:
similar_t

movie
Father of the Bride Part II (1995)    0.287343
GoldenEye (1995)                     -0.021940
Grumpier Old Men (1995)               0.277298
Heat (1995)                           0.059740
Jumanji (1995)                        0.054658
Sabrina (1995)                        1.000000
Sudden Death (1995)                   0.130281
Tom and Huck (1995)                   0.123087
Toy Story (1995)                      0.002798
Waiting to Exhale (1995)              0.132838
dtype: float64

In [46]:
sim = pd.DataFrame(similar_t,columns=["Correlation"])

In [47]:
sim

                                    Correlation
movie
Father of the Bride Part II (1995)     0.287343
GoldenEye (1995)                      -0.021940
Grumpier Old Men (1995)                0.277298
Heat (1995)                            0.059740
Jumanji (1995)                         0.054658
Sabrina (1995)                         1.000000
Sudden Death (1995)                    0.130281
Tom and Huck (1995)                    0.123087
Toy Story (1995)                       0.002798
Waiting to Exhale (1995)               0.132838

In [52]:
sim[sim["Correlation"]>0].sort_values(by="Correlation",ascending=False).head()

                                    Correlation
movie
Sabrina (1995)                         1.000000
Father of the Bride Part II (1995)     0.287343
Grumpier Old Men (1995)                0.277298
Waiting to Exhale (1995)               0.132838
Sudden Death (1995)                    0.130281